customhost = "employee.ca9mo8xwoogr.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "capc3009"
customdb = "employee"
custombucket = "yoongzhihong-employee"
customregion = "us-east-1"
